---

- name: Copy flanneld binary
  copy:
    src: "{{ BIN_DIR }}/flanneld"
    dest: "/usr/local/bin/"
    owner: root
    group: root
    mode: 0755

- name: Set flannel network conf on etcd
  uri:
    client_cert:  /var/lib/kubelet/{{ ansible_hostname }}.pem
    client_key: /var/lib/kubelet/{{ ansible_hostname }}-key.pem
    validate_certs: no
    url: https://10.0.0.100:2379/v2/keys/kubernetes-cluster/network/config
    body: "value={{ ETCD_NET_CONFIG }}"
    status_code: 200,201
    method: PUT
    return_content: yes
  run_once: true

- name: Copy flannel systemd unit file
  template:
    src: "lib/systemd/system/flannel.service.j2"
    dest: "/lib/systemd/system/flannel.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart flannel

- meta: flush_handlers
